import { Metadata } from "next";
import Navbar from "./component/Navbar";
import "./global.css";
export const metadata: Metadata = {
  title: {
    template: " %s | Netflick",
    default: "Netflick",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-slate-800 text-white">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
